pandas-stubs/core/frame.pyi, pandas-stubs/core/indexes/datetimes.pyi, pyproject.toml, tests/test_frame.py, tests/test_timefuncs.py
- For `DataFrame.__iter__()` return `Iterable[Hashable]` #30 
- For `DataFrame.loc[1, "abc"]`, allow `int` as first argument #32 
- For `DatetimeIndex`, add methods such as `isocalendar()` #31 
- For `DataFrame.join()` allow a mix of `Series` and `DataFrame` as `other` argument #29 
Bump version to 1.4.2.220622
=> Fixes for GH 29, 30, 31, 32

pyproject.toml
Moved the dependencies for `pandas`, `matplotlib` and `typing_extensions` to be dev only.
No tests added.  Tested locally to see that you can install the stubs without pandas and matplotlib being installed, and `pyright` and both `mypy` still will check source.
=> remove installation dependencies on pandas and matplotlib

scripts/test/__init__.py, scripts/test/_step.py
Errors in script were calling `pyright_src` instead of `pyright_dist` when testing the distribution.
=> run pyright_dist instead of pyright_src when testing dist

pandas-stubs/io/excel/_base.pyi, tests/test_frame.py
`pandas.read_excel` supports specifying `None` for `sheet_name`.
When using `None`, all worksheets are returned.
https://pandas.pydata.org/docs/reference/api/pandas.read_excel.html#pandas.read_excel
=> Fix error when `sheet_name` is `None` for `read_excel`.

tests/test_series.py, tests/test_testing.py
Catch expected warnings to reduce noise in testing
=> MAINT: Catch expected warnings

pandas-stubs/core/series.pyi, tests/test_series.py
https://pandas.pydata.org/docs/reference/api/pandas.Series.html#pandas-series
Closes #90
=> Make `index` in the `Series` ctor optional to match Pandas docs.

pandas-stubs/_typing.pyi, tests/test_series.py
=> Allow `num` to be a `complex` type to support `Series` operations.

pandas-stubs/core/tools/datetimes.pyi, tests/test_timefuncs.py
Have to_datetime returning NaTType when errors are coerced and scalar input
=> ENH: Overload to_datetime when errors="coerce"

.github/workflows/test.yml, pyproject.toml, scripts/test/__init__.py, scripts/test/_step.py, scripts/test/run.py
This should make `poe --help` easier to skim and clearer.
Happy to also rename `Steps` (in `scripts/test/_step.`py) and the github workflow steps, if the changes in pyproject.toml are okay.
=> Rename poe tasks

pandas-stubs/core/frame.pyi, tests/test_frame.py
Allow any scalar types in .loc to return a Series
xref #133
=> ENH: Improve DataFrame loc indexing

pyproject.toml
c/clean_cache is a flag to control whether to clear the mypy/pytest cache but `poe test_src -c` did not work (it expected an argument after c/clean_cache).
After making this keyword of type boolean, no argument is required: `poe test_src -c` works :)
=> make -c/--clean_cache a flag

pandas-stubs/core/frame.pyi, tests/test_frame.py
- `test_frame.py:test_types_set_index()` from original issue - added one test
=> fix args to DataFrame.set_index

pandas-stubs/_typing.pyi, pyproject.toml, scripts/test/__init__.py, scripts/test/_step.py, scripts/test/run.py
mypy is already called with `--no-incremental` which disables the cache. I simply added the corresponding flag for pytest, to remove this flag.
=> remove cache options

pandas-stubs/core/base.pyi, pandas-stubs/core/groupby/groupby.pyi, pandas-stubs/core/resample.pyi
- None
pandas has `BaseGroupBy` (which should be private), whereas the stubs had `_GroupBy`, but I wanted to get things aligned.  Probably `BaseGroupBy` should be private in pandas.
In addition, `SelectionMixin` is really an abstract class, so removing `aggregate` makes sense, as the pandas implementation raises an exception anyway.
=> CLEAN: Align Groupby types

.github/workflows/test.yml, docs/style.md, docs/tests.md, pyproject.toml
Add simpler task names to simplify running tools
=> ENH: Add default mypy and pyright tasks

pandas-stubs/_testing/__init__.pyi
`check_frame_typ` → `check_frame_type`
`check_frame_typ` does not appear in the parameters, I think this is most likely to be a typo.
https://pandas.pydata.org/docs/reference/api/pandas.testing.assert_frame_equal.html
Currently the type hint incorrectly produces this error in mypy:
```
error: Unexpected keyword argument "check_frame_type" for "assert_frame_equal"; did you mean "check_frame_typ"?
```
=> BUG: Fix typo on check_frame_type

pyproject.toml, scripts/test/__init__.py, scripts/test/run.py
will make it easier for #128 `poe stubtest --check_missing | grep "pandas\._typing"` @Dr-Irv
=> stubtest: option to not set ignore-missing-stub

pyproject.toml, scripts/test/__init__.py, scripts/test/_step.py, scripts/test/run.py
`poe stubtest --nightly --check_missing | grep "pandas\._typing"` for #128 @Dr-Irv 
conda nightly seems to have timeout issues: might get one or multiple of these warnings (and could even fail after 4 tries):
> WARNING: Retrying (Retry(total=4, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ReadTimeoutError("HTTPSConnectionPool(host='pypi.anaconda.org', port=443): Read timed out. (read timeout=15)")': /scipy-wheels-nightly/simple/pandas/
=> stbutest: option to use it with pandas nightly

pandas-stubs/_typing.pyi, pandas-stubs/core/frame.pyi, tests/test_frame.py
- `test_frame.py:test_dict_items()`
Also clean up use of `_ListLike` which was too broad for most of the methods in `frame.pyi`
=> allow dict_items in DataFrame constructor.  Clean up _ListLike

pandas-stubs/io/excel/_base.pyi, tests/test_frame.py
pandas.read_excel is documented to accept
> str, bytes, ExcelFile, xlrd.Book, path object, or file-like object
This expands the annotation to include str, bytes, paths,
and file-likes. Bytes are coerced into a BytesIO inside ExcelReader.
=> read_excel accepts PathLike, buffers

pandas-stubs/core/reshape/pivot.pyi, tests/test_pandas.py
These are allowed ([docs page](https://pandas.pydata.org/docs/reference/api/pandas.crosstab.html?highlight=crosstab#pandas.crosstab)).
=> Allow strings to crosstab's normalize argument

pandas-stubs/core/frame.pyi, pandas-stubs/core/series.pyi, tests/test_frame.py
- Added the option to pass `None` as `axis` in `DataFrame.all\any`.
- Fixed the return type to be `Series[bool]` instead of just `Series`.
=> Fixed axis and return types for DataFrame.all/any

pandas-stubs/core/frame.pyi, pandas-stubs/core/series.pyi, tests/test_frame.py, tests/test_series.py
Deprecated the `level` argument for several functions, in accordance to the pandas documentation.
=> Deprecated the level argument

pandas-stubs/core/frame.pyi, pandas-stubs/core/reshape/pivot.pyi, tests/test_frame.py
Just a general question: Can we type lib.NoDefault here?
=> Type pivot arguments

pandas-stubs/core/frame.pyi, pandas-stubs/core/series.pyi, tests/test_frame.py
* Cleaned up typing on `Series.__new__, DataFrame.__new__`.
* Allowed `DataFrame` to be created from a scalar and index/columns.
=> Seris and DataFrame creation typing

.github/workflows/test.yml
=> MAINT: Show python info on Windows

.github/workflows/test.yml
We had pinned poetry to 1.1.15 when we were testing the Windows CI issues.  This removes that.
=> unpin poetry

.github/setup/action.yaml, .github/workflows/test.yml, pyproject.toml, scripts/test/__init__.py, scripts/test/run.py, tests/test_frame.py, tests/test_io.py
Not sure whether it will succeed if pytest fails.
=> run pytest against nightly

pyproject.toml
conda-forge build broke because `types_SQLAlchemy` is not a conda package.   Apparently, it is automatically built from whatever is in typeshed.
Removing it to see if it passes CI.
=> remove types_SQLAlchemy dependency

pandas-stubs/core/generic.pyi, pandas-stubs/io/sql.pyi, pyproject.toml, tests/test_io.py
The typecheck for sql io api developed in https://github.com/pandas-dev/pandas-stubs/commit/4c97ed3d8be74b6e982889f177dc6228b788e4da does not accept `sqlalchemy.engine.Engine` for the argument `con`. 
However, the original pandas implementation accepts them
* https://pandas.pydata.org/docs/reference/api/pandas.DataFrame.to_sql.html
* https://pandas.pydata.org/docs/reference/api/pandas.read_sql.html
In fact, `pandasSQL_builder`, which is used in [`to_sql`](https://github.com/pandas-dev/pandas/blob/main/pandas/io/sql.py#L687) and [`read_sql`](https://github.com/pandas-dev/pandas/blob/main/pandas/io/sql.py#L562), requires `sqlalchemy.engine.Connectable` not only `sqlalchemy.engine.Connection`:
https://github.com/pandas-dev/pandas/blob/50c119dce9005cb3e49c0cfb89f396aeecab94f1/pandas/io/sql.py# …
=> Accept `sqlalchemy.engine.Engine` for SQL IO API (`read_sql`, `to_sql`)

pandas-stubs/__init__.pyi
The double-import of `pandas.testing` in `__init__.pyi` breaks detection of this module in pyright. Fixup by removing the unneeded absolute import in favor of the existing relative import used for other submodules.
=> Fix inclusion of pandas.testing in __init__.pyi

.github/workflows/test.yml
Because of the bug in `mypy` with python 3.10.7 (see https://github.com/pandas-dev/pandas-stubs/issues/296#issuecomment-1245527765) that has links to various mypy issues on this topic, we need to pin python 3.10 to 3.10.6 in the CI
=> try pinning python 3.10 to 3.10.6

pandas-stubs/_config/config.pyi, tests/test_config.py
Generalize using specific classes for each level
=> BUG: Generalize options

pandas-stubs/core/arrays/datetimes.pyi, pandas-stubs/core/arrays/period.pyi, pandas-stubs/core/arrays/timedeltas.pyi, pandas-stubs/core/indexes/accessors.pyi, pandas-stubs/core/indexes/datetimes.pyi, pandas-stubs/core/indexes/timedeltas.pyi, tests/test_timefuncs.py
- `test_timefuncs.py:test_timedeltaindex_accessors()`
Notes:
1. For some reason, I couldn't use the existing classes to hook in the rounding methods, so had to duplicate them for `TimedeltaIndex`.  Maybe it is because `DatetimeIndex` and `TimedeltaIndex` have a common base class.  In `_DTRoundingMethodReturnType`, just changing the order of `DatetimeIndex` and `TimedeltaIndex` causes different failures with pyright.  Maybe doing `Generic[SomeTypeVar]` doesn't work if the classes for `SomeTypeVar` share some common base class.  mypy was OK with doing things this way.
2. Adding this feature caused mypy to complain about using `dtl` to represent a module in some of the array classes, so I removed it and explicitly imported the classes.
=> Add accessors for TimedeltaIndex

pandas-stubs/core/frame.pyi, pandas-stubs/core/series.pyi, tests/test_frame.py, tests/test_series.py
=> Support Callable conditions for DataFrame.where() and Series.where()

pandas-stubs/core/frame.pyi, pandas-stubs/core/series.pyi, tests/test_frame.py, tests/test_series.py
- `test_frame.py`
- `test_setitem_loc()`
- `test_replace_na()`
- `test_series.py`:  New test in `test_types_fillna()`
=> Fix replace, fillna allowing pd.NA.  Allow list of arguments for .loc

pandas-stubs/_typing.pyi, pandas-stubs/core/indexing.pyi, tests/test_frame.py
- `test_frame.py:test_indexslice_getitem()`
=> Index slice

pandas-stubs/io/sql.pyi, tests/test_io.py
Allow sqlalchemy TextClause for sql select statements
=> ENH: Allow TextClause

pandas-stubs/core/series.pyi, tests/test_timefuncs.py
```
In [2]: import pandas as pd
...: from datetime import datetime
...: s = pd.Series(pd.date_range("1/1/2020", "2/1/2020"))
...: s - datetime.now()
Out[2]: 
0    -995 days +02:03:18.373842
1    -994 days +02:03:18.373842
2    -993 days +02:03:18.373842
3    -992 days +02:03:18.373842
4    -991 days +02:03:18.373842
5    -990 days +02:03:18.373842
6    -989 days +02:03:18.373842
7    -988 days +02:03:18.373842
8    -987 days +02:03:18.373842
9    -986 days +02:03:18.373842
10   -985 days +02:03:18.373842
11   -984 days +02:03:18.373842
12   -983 days +02:03:18.373842
13   -982 days +02:03:18.373842
14   -981 days +02:03:18.373842
15   -980 days +02:03:18.373842
16   -979 days +02:03:18.373842
17   -978 days +02:03:18.373842
18   -977 days +02:03:18.373842
19   -976 days +02:03:18.373842 …
```
=> Allow datetime values to be subtracted from a Series to create a TimedeltaSeries

pandas-stubs/_libs/tslibs/offsets.pyi, pandas-stubs/core/frame.pyi, pandas-stubs/core/indexes/accessors.pyi, pandas-stubs/core/indexes/datetimes.pyi, pandas-stubs/core/indexing.pyi, pandas-stubs/core/series.pyi, tests/test_frame.py, tests/test_series.py, tests/test_timefuncs.py
Fixed some issues found when writing some new code and checking some old code:
- `test_frame.py:test_types_drop()` modified to check `Index` as argument
-  `test_series.py:test_types_drop()` modified to check `Index` as argument
- Added tests for `IndexSlice` in existing test functions
- Fixed up test for `tz_localize()` and related methods that follow
- Added tests for `WeekOfMonth` and `LastWeekOfMonth`
=> fix issues 302, 314, 320, 321

pandas-stubs/_typing.pyi, pandas-stubs/core/frame.pyi, pandas-stubs/core/series.pyi, pandas-stubs/core/window/ewm.pyi, tests/test_windowing.py
=> ENH: Add step to rolling

pyproject.toml
=> Remove use of removed mypy option

pandas-stubs/_typing.pyi
This will avoid the new behavior/regression in mypy 0.981https://github.com/python/mypy/issues/13760
=> TYP: de-duplicate some type unions

pandas-stubs/api/interchange/__init__.pyi, pandas-stubs/core/frame.pyi, pandas-stubs/core/interchange/dataframe_protocol.pyi, pandas-stubs/core/interchange/from_dataframe.pyi
=> ENH: add from_dataframe and DataFrame

pandas-stubs/__init__.pyi, pandas-stubs/core/computation/eval.pyi, pandas-stubs/core/util/hashing.pyi, tests/test_pandas.py
=> ENH: Improve hashing and eval

pandas-stubs/_typing.pyi, pandas-stubs/core/indexes/base.pyi, pandas-stubs/core/indexes/interval.pyi, tests/test_indexes.py
=> ENH: Imprpve interval_range and IntervalIndex

pandas-stubs/io/excel/_base.pyi, tests/test_io.py
=> Change ExcelWriter modes to {"w","a"}

pandas-stubs/core/dtypes/missing.pyi, tests/test_pandas.py
Putting up a draft first because I actually am not quite sure what the best way to go about this is. I wrote the tests first, as to what the behavior intuitively should be, but getting the annotations to match is the challenging part.
Further, I'm still not perfectly happy with these annotations, because I have seen tons of code use `pd.isnull` on any random object, and the annotations currently do not support this, they only really allow `pandas` objects and a curated list of `Scalar` objects.
=> Turn isna() and notna() into TypeGuards

.gitignore, pandas-stubs/core/frame.pyi, pandas-stubs/core/series.pyi, tests/test_windowing.py
=> Allow str to be passing to rolling() window and use IntervalClosedType literal for series as well

pyproject.toml
[PyPI](https://pypi.org/project/pandas-stubs/) shows both “Repository” and “Source Code”:
I guess “Repository” comes from Poetry, so you don’t need a second declaration.
=> Remove redundant PyPI link “Source code”

pandas-stubs/_testing/__init__.pyi, tests/test_testing.py
Add default arg for overload
closes #417
=> BUG: Fix assert_series_equal

pandas-stubs/_libs/tslibs/offsets.pyi, tests/test_timefuncs.py
=> Support time start/end for BusinessHour & CustomBusinessHour

pandas-stubs/core/series.pyi, tests/test_series.py
Sir can you please check the tests.
=> Added ArrayLike In Series.clip

pandas-stubs/core/groupby/generic.pyi, tests/test_frame.py
=> Changed SeriesGroupBy to return Series

pandas-stubs/core/frame.pyi, pandas-stubs/core/series.pyi, tests/test_frame.py
- No `assert_type` because it is testing `__setitem__()`
- `test_frame.py/test_setitem_none()`
Either @twoertwein or @bashtage can review/approve/merge.
=> Allow None in .loc.__setitem__ and .iloc.__setitem__

pandas-stubs/io/parsers/readers.pyi, tests/test_frame.py
If it accepts a `Dict[int | str, ...]` it should accept a `Dict` of either key type.
=> Permit covariance of key type in read_csv converters argument

pandas-stubs/core/groupby/generic.pyi, tests/test_frame.py
Follow up PR for #445 
Added the two value_counts method as told, tried to change the tests but I have some questions here:-
1) Sir actually when I write  test `check(assert_type(c1, pd.Series[int]), pd.Series, pd.Series[int])`
it shows  this error `Type application has too few types (2 expected)  [misc]` it only works when we write the test like
this `check(assert_type(c1, pd.Series[int]), pd.Series)`
2) and when the above change is made pytest does not work it shows this error `type' object is not subscriptable`
and only works when we write the test like `check(assert_type(c1, pd.Series), pd.Series)` but `mypy` fails here it says `Expression is of type "Series[float]", not "Series[Any]"  [assert-type]`
3) @Dr-Irv  Sir the recent changes you made in test_pandas.py in line 1443 also shows …
=> Follow up PR for changes requested in #445

pandas-stubs/_typing.pyi, pandas-stubs/core/frame.pyi, tests/test_frame.py
In #401 the annotations for `apply` was changed. This introduced false negatives in my code base, because the particular mix of return types and arguments I was using was not supported. Here I am still not sure it is exhaustive but I think it's an improvement. In particular the `result_type` needs to be accounted for, as well as differentiating between a true list-like, `str`, and `Series` in the return value of the function.
@Dr-Irv @bashtage @danielroseman
=> Fix annotations for DataFrame.apply() including additional overloads

.pre-commit-config.yaml, pyproject.toml, tests/test_api_types.py, tests/test_frame.py, tests/test_io.py, tests/test_timefuncs.py
=> TST: run all tests

pandas-stubs/_typing.pyi, tests/test_io.py
Includes the Literal `table` for the `orient` argument in s.to_json().
=> feat: add `table` to JsonSeriesOrient Literals

pyproject.toml, tests/__init__.py, tests/test_frame.py
pyright 1.1.286 fixed an issue that didn't allow users to write `df.columns = ["abc", "def"]`.
Our testing code was not picking this up because we had `#type: ignore` comments on the testing code, which are needed because of a mypy bug.
So I've instrumented the test to be checked with `pyright`, but not `mypy`.  Unfortunately, `mypy` doesn't support a `mypy: ignore` comment.
- Issue reported to pyright  was here:  https://github.com/microsoft/pyright/issues/4293
- Discussion on how to see which type checker is being used is here:  https://github.com/microsoft/pyright/issues/4292
=> fix: test setter on df.columns with pyright, not mypy

pandas-stubs/core/frame.pyi, pandas-stubs/core/indexing.pyi, pandas-stubs/core/series.pyi, tests/test_frame.py
- `test_frame.py:test_getsetitem_multiindex()`
=> allow multiindex for a column in DataFrame.loc

pandas-stubs/core/series.pyi, tests/test_series.py
- `test_series.py:test_pandera_generic()`
Fix here is to expand the `Series[IntervalT].__new__()` into each individual part.  Seems like a double `TypeVar` causes issues for `mypy`.  Had to do a similar fix for `Interval.__contains__()`
Either @twoertwein or @bashtage can approve or merge (both not required)
=> Fix issue for pandera allowing generic Series to work

pyproject.toml
CI is failing because SQLAlchemy 1.4.46 issues a warning that is not issued with 1.4.45.  So pin SQLAlchemy 1.4.45 here.
pandas issue created at https://github.com/pandas-dev/pandas/issues/50558
=> pin SQLAlchemy to 1.4.45

pandas-stubs/core/frame.pyi, tests/test_frame.py
=> added datatypes for dropna subset as per pandas-dev#434

tests/test_timefuncs.py
Just made the test depend on the pandas version
Either @twoertwein or @bashtage can review, approve or merge.  Both approvals not needed.
=> fix nightly build with Series.to_numpy() on a Timedelta series

pandas-stubs/core/indexes/interval.pyi, pandas-stubs/core/series.pyi, tests/test_timefuncs.py
Turns out that I misunderstood the use of `Never`, and we don't need to use it.  See https://github.com/pandas-dev/pandas-stubs/issues/441#issuecomment-1379450907 .
=> Remove use of Never

.github/pull_request_template.md, .github/workflows/test.yml, .pre-commit-config.yaml, docs/tests.md, pyproject.toml, scripts/test/__init__.py, scripts/test/_step.py, scripts/test/run.py
Add an option to easily test the stubs with mypy nightly. Might be important to do that whenever mypy is close to a new release (especially if mypy advertises pandas-stubs, see https://github.com/python/mypy/issues/14328).
Mypy nightly reports two unused ignores, so I didn't enable it on the CI.
`poe --help`:
=> Optionally run tests with mypy nightly

tests/test_indexes.py, tests/test_timefuncs.py
Nightly builds were failing because `NumericIndex` is removed for 2.0, so this allows it to work for 1.5.x, but removes it from testing for 2.0. 
Once 2.0 is released, then we can remove `NumericIndex` in the PYI and tests.
=> fix NumericIndex for nightly

pandas-stubs/_libs/tslibs/timestamps.pyi, pandas-stubs/_typing.pyi, pandas-stubs/core/series.pyi, tests/test_scalars.py, tests/test_timefuncs.py
Turns out that it is not possible to have a `Series` containing `np.datetime64` types - they get converted to `Timestamp`.  Discovered this with some experiments that showed we were allowing two `Series` of `Timestamp` to be added, which is not possible, so fixed that as well.
=> remove np.datetime64 from S1, make adding two TimestampSeries fail

pandas-stubs/core/series.pyi, tests/test_series.py
=> add Series to Series.between

pandas-stubs/core/indexes/base.pyi, tests/test_frame.py, tests/test_indexes.py
- `test_frame.py/test_in_columns()`
Without this fix, the following code reports errors:
```python
import pandas as pd
import numpy as np
df = pd.DataFrame(np.random.random((3,4)), columns=["cat", "dog", "rat", "pig"])
cols = [c for c in df.columns if "at" in c]
print(df[cols])
```
pyright then reports:
```text
colcheck.py:5:34 - error: Operator "in" not supported for types "Literal['at']" and "IndexIterScalar | tuple[Hashable, ...]"
  Operator "in" not supported for types "Literal['at']" and "bytes"
  Operator "in" not supported for types "Literal['at']" and "date"
  Operator "in" not supported for types "Literal['at']" and "datetime"
  Operator "in" not supported for types "Literal['at']" and "timedelta"
  Operator "in" not supported for types "Literal['at']" and "bool"
  Operator "in" …
```
=> remove types from Index.__iter__()`

pandas-stubs/core/indexes/interval.pyi, tests/test_interval_index.py
Thank you for always maintaining this stub!
It contributes greatly to the robustness of Python programs using pandas.
`IntervalIndex` has [`to_tuples` method](https://pandas.pydata.org/docs/reference/api/pandas.IntervalIndex.to_tuples.html), but its stub is currently missing.
Add a stub for `IntervalIndex#to_tuples` and a test for it.
Note that the documentation above states that the return type of that method is an ndarray,
but it is actually `Index` (the test to be added checks for this).
This appears to be a mistake in the pandas doc.
(Probably the doc for `IntervalArray#to_tuples` is also being used for `IntervalIndex#to_tuples`, and since `IntervalArray#to_tuples` does indeed return an ndarray, it is incorrectly showing up in the doc for `IntervalIndex#to_tuples` as well.)
=> ENH: Add `to_tuples` method to `IntervalIndex`

pandas-stubs/core/algorithms.pyi, pandas-stubs/core/indexes/interval.pyi, tests/test_interval_index.py
`pd.DataFrame(some_data, pd.IntervalIndex(...))` did not work as `IntervalIndex` was not declared as a subclass of `Index`.
For some reason `poe pyright` creates 800+ errors for me locally - it doesn't find any of the packages (including pandas/pytest/numpy/...) Using the CI to find the pyright errors for now.
=> IntervalIndex is a subclass of Index

pandas-stubs/_typing.pyi, tests/test_pandas.py
* Update `IndexIterScalar` to include `np.datetime64` and `np.timedelta64`
* Update `test_isna` to include tests for `np.datetime64` and `np.timedelta64`
=> Fixes mypy error when passing `np.datetime64/timedelta64` input to `pd.isna`

pandas-stubs/_config/config.pyi, tests/test_config.py
Set the correct type for pd.options.display.float_format.
=> gh-544: Fix pd.options.display.float_format

pandas-stubs/_typing.pyi, tests/test_frame.py, tests/test_series.py
=> Support `DataFrame.astype('category')`

pandas-stubs/_typing.pyi, tests/test_series.py
@Dr-Irv FYI @ramvikrams @skatsuta
=> Support all possible time units for Series.astype literals

tests/__init__.py, tests/test_frame.py
Nightly was failing due to features for 2.1 so added a test for 2.0 to fix that.
=> test for groupby axis=1 for v2.0 or less

pandas-stubs/core/frame.pyi, pandas-stubs/core/generic.pyi, pandas-stubs/core/series.pyi, tests/test_frame.py, tests/test_series.py
`axis=1` still fails pytest I have tried everything it shows a `Key Error`
=> gh:524 - xs method added to series and frame.pyi

.github/workflows/optional.yml, .github/workflows/test.yml
=> CI: run nightly tests only on main

pandas-stubs/core/frame.pyi, tests/test_frame.py
The result type of `DataFrame.align` should be a tuple instead of `DataFrame`.
=> Fix result type of `DataFrame.align`

scripts/test/run.py
Seems to work for me locally. I think the issue is that the nightly index overwrote the normal pypi index so it didn't find any other packages.
=> CI: nightly builds from additional index

README.md
Fixed a few grammatical issues in the README(Background and Differences between type declarations in pandas and pandas-stubs)
=> Checked README.md grammar and spelling

pandas-stubs/core/series.pyi, tests/test_series.py
When running `poe test_all`, my new test passes, but it seems that one* test (that wasn't modified by my commits) doesn't pass:
```py
Success: no issues found in 224 source files
===========================================
End: 'Run mypy on 'tests' (using the local stubs) and on the local stubs', runtime: 29.387 seconds.
===========================================
===========================================
End: 'Run pyright on 'tests' (using the local stubs) and on the local stubs', runtime: 12.964 seconds.
===========================================
```
\* pytest one:
```py
================================================= test session starts =================================================
platform win32 -- Python 3.10.2, pytest-7.2.2, pluggy-1.0.0
rootdir: …
```
=> Fixed apply stubs when using a function returning a set

tests/test_series.py
=> gh:610 - added warnings 

tests/test_series.py
=> corrected the message for PR 611

tests/test_series.py
=> updated message for PR 611

tests/test_series.py
=> updated message- PR 611

pandas-stubs/core/series.pyi
I noticed that we had two references to `Series[Timestamp]` and `Series[Timedelta]` in methods, and those methods were `__sub__()`, so I removed them from `Series` and placed them in `TimestampSeries`, and I think this fixes the mypy nightly problem.  
Tested mypy nightly locally and it worked.  So if this passes CI, then mypy_nightly could be tested by doing a merge.
=> Fix mypy nightly

tests/test_series.py
=> updated the lower bound PR 611

pyproject.toml
=> Remove cap on python version

pandas-stubs/_typing.pyi, pandas-stubs/io/clipboards.pyi, pandas-stubs/io/excel/_base.pyi, pandas-stubs/io/parsers/readers.pyi, tests/test_io.py
Submitted as 1 PR for the 2 issues because the relevant code is so close that I thought it might be quicker to review together, plus trying to have both as separate PRs would likely result in merge conflicts if/when one was merged before the other. The commits addressing the two issues are separate though, so it would be easy for me to split into 2 separate PR if this is preferred.
As well as read_csv, modify read_table, read_clipboard, read_excel, which all have the relevant params (I searched for other functions but let me know if I missed any).
Closes #605 in a different way than suggested in that ticket, in order to allow broader types than just lists of string or ints, since list-likes are allowed here. Naming of the type alias UsecolsArgType was inspired by ColspaceArgType, happy to …
=> Broaden read csv param types

docs/philosophy.md
- no issue closed (I could open one for the type, or others for the other changes, but it seems a small enough change to not be worth it - happy to if you would prefer though!
- no tests added - docs-only change.
While working on #630 and reading docs/philosophy, I noticed a 'too' typo for 'to', which I thought I'd fix (in the first commit in the PR).
While making that change though, I noticed a couple of inconsistencies in the same paragraph:
1. In the number of spaces after a '.' (full stop/period) at the end of a sentence - normally 2 spaces, but sometimes 1.
2. Some lines have trailing whitespace (while most don't)
I fixed these for the paragraph, but also the rest of the document (using the regex `\. ([^ ])` for the whitespace after '.', and `\s$` for the trailing whitespace.
=> Cleanup philosophy doc

.pre-commit-config.yaml, pyproject.toml
I'm getting some pyright issues locally. Let's see which version of pyright the CI picks.
=> Update mypy to 1.2.0

pandas-stubs/_typing.pyi, pandas-stubs/core/resample.pyi, pandas-stubs/core/series.pyi, tests/test_frame.py, tests/test_resampler.py, tests/test_series.py, tests/test_windowing.py
=> gh:552 - Corrected Series.mean return type

README.md
At today's pandas core dev meeting, we decided to go ahead with releasing a 2.0 version of the stubs that is not fully compatible with pandas 2.0.  This PR updates the README to reflect a message indicating that fact.
Once merged, I will do a release of the stubs.
=> update README to indicate level of 2.0 support

pandas-stubs/_typing.pyi, pandas-stubs/core/series.pyi, tests/test_frame.py, tests/test_resampler.py, tests/test_series.py, tests/test_windowing.py
Reverts pandas-dev/pandas-stubs#622 for issue #646
=> Revert "gh:552 - Corrected Series.mean return type"

tests/test_api_types.py, tests/test_dtypes.py, tests/test_frame.py, tests/test_series.py, tests/test_timefuncs.py
There is still a TypeError on nightly xref https://github.com/pandas-dev/pandas/issues/52790 (will mark as invalid - there is no warning but it will raise in 2.1: I think we should reflect that in our annotations)
=> Fix pandas-nightly

pandas-stubs/_typing.pyi, pandas-stubs/io/sql.pyi, tests/test_io.py
=> GH - 624: Added `dtype` arg to `read_sql`

pandas-stubs/core/generic.pyi, pandas-stubs/core/series.pyi, pandas-stubs/core/tools/numeric.pyi, pandas-stubs/io/clipboards.pyi, pandas-stubs/io/excel/_base.pyi, pandas-stubs/io/feather_format.pyi, pandas-stubs/io/html.pyi, pandas-stubs/io/json/_json.pyi, pandas-stubs/io/orc.pyi, pandas-stubs/io/parsers/readers.pyi, pandas-stubs/io/spss.pyi, pandas-stubs/io/sql.pyi, pandas-stubs/io/xml.pyi, tests/test_frame.py, tests/test_io.py, tests/test_series.py
=> GH: 624 - Added `dtype_backend` to all `read_*` functions

tests/test_api_types.py, tests/test_frame.py, tests/test_io.py
=> nightly fix for GH-657

pandas-stubs/core/algorithms.pyi, tests/test_pandas.py
Needed to pass `df.to_records` which returns an `np.recarray` directly to `pd.factorize`
=> add support for `np.recarray` in `pd.factorize`

scripts/test/__init__.py, scripts/test/run.py, tests/test_api_types.py, tests/test_frame.py, tests/test_io.py, tests/test_series.py, tests/test_timefuncs.py
closes #666
`pytest_warns_bounded` becomes unused with this PR
=> CI: ignore warnings from pandas-nightly

pandas-stubs/core/indexes/interval.pyi, pandas-stubs/core/indexes/timedeltas.pyi, pandas-stubs/core/series.pyi, tests/test_indexes.py, tests/test_series.py, tests/test_timefuncs.py
Had a little time so closed out a few "good first issues"
- `test_series.py: test_apply_returns_none()`
- `test_series.py: test_loc_callable()`
- Various tests for `timedelta_range()` and `interval_range()` with `timedelta` arguments.
=> close out a few first issues

pandas-stubs/_typing.pyi, tests/test_io.py
=> GH-676 : Corrected `DtypeArg` for accepting strings

pandas-stubs/io/sql.pyi, pyproject.toml, tests/test_io.py
Based on https://github.com/pandas-dev/pandas/issues/50558#issuecomment-1537477148, we could upgrade SqlAlchemy to 2.0.  Doing that revealed an issue in those tests and some of the typing.
Also bumped pyright to 1.1.306, but the default value for `useLibraryCodeForTypes` changed in that version, so added that in `pyproject.toml`.  Without that, some of the plotting tests fail because `matplotlib` doesn't have typing yet.
=> upgrade SQLAlchemy and pyright

pandas-stubs/core/frame.pyi, pandas-stubs/core/groupby/generic.pyi, tests/test_frame.py
=> Fix inplace overload for DataFrame.interpolate

pandas-stubs/core/frame.pyi, pandas-stubs/core/series.pyi, tests/test_windowing.py
=> Allow Timedelta for `Series.rolling` and `DataFrame.rolling`

pandas-stubs/api/__init__.pyi, tests/test_api_types.py
It seems that tests need to be added, but not sure which folder should be added and may need some help
=> Add interchange to `pandas-stubs/api/__init__.pyi`

pandas-stubs/core/frame.pyi, tests/test_frame.py
=> DataFrame__getitem__: accepts generator

pandas-stubs/core/series.pyi, tests/test_series.py
=> Argument 1 to "apply" of "Series" has incompatible type "Callable[[Any], Union[int, NAType]]"

pandas-stubs/_libs/tslibs/timestamps.pyi, pyproject.toml, tests/test_io.py
=> numpy 1.25.0, pyright 1.1.316, mypy 1.4.1

tests/test_api_types.py, tests/test_frame.py, tests/test_io.py, tests/test_pandas.py, tests/test_resampler.py, tests/test_series.py, tests/test_styler.py, tests/test_timefuncs.py, tests/test_windowing.py
Added a number of `pytest_warns_bounded()` to catch warnings.  Discovered a few errors in the pandas dev code which are reported as issues there.
=> fix nightly tests to work with 2.1 dev code

pandas-stubs/io/sql.pyi, tests/test_io.py
Align parameter type to SQL functions: https://github.com/pandas-dev/pandas/blob/main/pandas/io/sql.py#L370
=> Fix SQL parameter type

pandas-stubs/_typing.pyi, pandas-stubs/core/series.pyi, tests/test_series.py
- pandas nullable `UInt` data types were missing
- numpy type code literals
- numpy alternative literals (half, short, double, etc.)
- pyarrow literals
- added `DtypeObj | _str` to final `astype` overload (resulting in `Series[Any]`)
- added few tests
- fixed random bug: `def __getattr__(self, name: str) -> S1` accidentally using `str` instead of `_str`.
=> added pyarrow/numpy dtype literals and allowed `str` | `DtypeObj` as input for `Series.astype`

pandas-stubs/core/series.pyi, pyproject.toml, tests/test_indexes.py, tests/test_pandas.py, tests/test_timefuncs.py
- `test_timefuncs.py:test_timedelta64_and_arithmatic_operator()` - added tests there
=> make sub of timedelta work

.pre-commit-config.yaml, pandas-stubs/_typing.pyi, pandas-stubs/core/frame.pyi, pandas-stubs/core/indexes/period.pyi, pandas-stubs/core/series.pyi, pyproject.toml, tests/test_frame.py, tests/test_indexes.py, tests/test_pandas.py, tests/test_series.py
=> Infer dtype of Series in more cases

.github/workflows/test.yml, .pre-commit-config.yaml, pandas-stubs/_libs/tslibs/timestamps.pyi, pandas-stubs/core/base.pyi, pyproject.toml, scripts/_job.py, tests/test_api_types.py, tests/test_dtypes.py, tests/test_frame.py, tests/test_indexes.py, tests/test_io.py, tests/test_pandas.py, tests/test_plotting.py, tests/test_resampler.py, tests/test_series.py, tests/test_styler.py
Ruff took care of all the code changes :)
I did not upgrade pandas itself.
=> Pandas 2.1 requires python>3.9

.pre-commit-config.yaml, pyproject.toml, scripts/test/run.py, tests/test_io.py
See https://github.com/microsoft/pyright/issues/6044#issuecomment-1741429961
=> CI: use compiled nightly mypy

pandas-stubs/_typing.pyi, pandas-stubs/core/indexes/base.pyi, pandas-stubs/core/series.pyi
When specifying the generic type of IntervalSeries, the current mypy also sees it as an error.
=> 'Fix' mypy-nightly

pandas-stubs/_typing.pyi, tests/test_io.py
=> Sync Usecols with pandas

README.md, docs/setup.md
ref: https://github.com/pandas-dev/pandas-stubs/blob/9aac8e31ba69eb4c0583e55dd2198755fb031620/pyproject.toml#L33
If you attempt to use version 3.8:
```zsh
❯ poetry env use 3.8
The currently activated Python version 3.8.18 is not supported by the project (>=3.9).
Trying to find and use a compatible version.
```
=> Update required python version to >= 3.9 in docs

README.md, docs/setup.md, pyproject.toml
The `*.dev-dependencies` section and the `--dev` flag of the `poetry add` command are deprecated. You will receive if you run:
```zsh
❯ poetry add --dev foo-pkg
The --dev option is deprecated, use the `--group dev` notation instead.
```
Instead, use groups (`*.group.dev.dependencies`):
```zsh
❯ poetry add foo-pkg --group dev
```
---
refs:
- https://python-poetry.org/docs/cli/#options-4
- https://python-poetry.org/docs/managing-dependencies/#dependency-groups
=> Use the new poetry dev dependency group

pandas-stubs/core/frame.pyi, tests/test_frame.py
According to [the pandas document](https://pandas.pydata.org/docs/reference/api/pandas.DataFrame.loc.html)
> A single label, e.g. 5 or 'a', (note that 5 is interpreted as a label of the index, and never as an integer position along the index).
dataframe.loc can accept int label, but for the previous stubs,`df.loc[1]` or similar codes would be warn.
=> Fix: dataframe.loc int label could be warn

tests/test_io.py, tests/test_pandas.py
Had failures as of 12/18, so this fixes them.
=> fix nightly tests

pyproject.toml
I am guessing that the MacOS failures in testing are due to the version of pytables.  Let's see if this fixes it.
=> pin tables to 3.9.1

pandas-stubs/_typing.pyi, pandas-stubs/core/series.pyi
I honestly would prefer to remove `OffsetSeries` and replace it with `Series[Any]` (personally, I'm not keen on maintaining operators for Series as there is no generic solution #820). If we want to keep this class, it would make sense to let it inherit from `Series[BaseOffset]` instead of `Series[Any/Unknown]`
=> OffsetSeries inherits from Series[BaseOffset]

pandas-stubs/_typing.pyi, pandas-stubs/core/frame.pyi, pandas-stubs/core/generic.pyi, tests/test_frame.py, tests/test_series.py
Follow up to https://github.com/pandas-dev/pandas/issues/56359. Type out `args` and `kwargs` in `pipe` methods, and make all instances of the `pipe` method consistent in their typing ( #738).
=> Type `args` and `kwargs` in `pipe`

pandas-stubs/core/frame.pyi, tests/test_frame.py
Make `DataFrame#loc` return `Series` or `DataFrame` if a scalar is given, to fix #749.
=> Make `DataFrame#loc` return `Series` or `DataFrame` if a scalar is given

pandas-stubs/core/frame.pyi, tests/test_frame.py
As promised in https://github.com/pandas-dev/pandas-stubs/issues/846#issuecomment-1880005640
The overlap in overloads is necessary as a dict with only scalar values returns a series but a dict with lists *and optionally scalar values* returns a dataframe. So both overloads have to accept scalar values but that doesn't seem to be a problem as both mypy and pyright are able to infer the good overload.
=> Fix calling df.agg with scalar dict values

pandas-stubs/core/reshape/concat.pyi, tests/test_pandas.py
=> Fix pd.concat to accept None values as input.

.pre-commit-config.yaml, pandas-stubs/core/reshape/concat.pyi, tests/test_pandas.py
closes #879
Works on pyright - mypy behaves weirdly (the 3rd overload is clearly the first matching overload). @Dr-Irv, feel free to change this PR - not sure whether I will have time to debug the mypy issue before the weekend.
=> fix concat for axis=0

pandas-stubs/core/tools/datetimes.pyi, tests/test_timefuncs.py
=> Fix to_datetime([dt.date]) (#891)

pandas-stubs/core/frame.pyi, tests/test_frame.py
This pull request addresses _issue #885_ by modifying the _pivot_table_ stub definition in _frame.pyi_ to allow lists of strings as the values argument. Previously, the stub definition only supported single strings or None for values.
**Changes Introduced:**
Updated the values argument type in the _pivot_table_ stub definition to include _Sequence[_str]_. This allows lists of strings to be used for values.
**Test Case:**
No test case added as there was already an existing test case in the file test_frame.py on line 922 : 
check(
```
assert_type(
df.pivot(index="col1", columns="col3", values=["col2", "col4"]),
pd.DataFrame,
),
pd.DataFrame,
)
```
Which already test the addressed issue and updated fix.
[ ] Closes #885
=> Fixed TYP of values argument of the pandas.DataFrame.pivot_table 

pandas-stubs/_libs/tslibs/timestamps.pyi, pandas-stubs/core/frame.pyi, tests/test_frame.py
=> 896 dataframe from dict columns dtype args

pandas-stubs/core/frame.pyi, tests/test_frame.py
I tried include with overloads limitations stated in `select_dtypes` documentation: 
> ValueError
> - If both of include and exclude are empty
> - If include and exclude have overlapping elements
> - If any kind of string dtype is passed in.
I managed to cover somehow the first tick covering when neither of include or exclude is provided but I am not sure that it is worth the introduced complexity in stubs.
=> 887 select_dtypes stubs fixing

pandas-stubs/_typing.pyi, pandas-stubs/io/excel/_base.pyi, pyproject.toml, tests/test_io.py
Since https://github.com/pandas-dev/pandas/pull/54998
No existing tests covering `engine`, I can add if needed?
=> Add calamine Excel reader

pandas-stubs/core/series.pyi, tests/test_frozenset.py, tests/test_series.py
When trying to use series.Apply() on "frozenset", it raises the following error:
error: Argument 1 to "apply" of "Series" has incompatible type "type[frozenset[Any]]"; expected "Callable[..., str | bytes | date | datetime | timedelta | datetime64 | timedelta64 | bool | int | float | Timestamp | Timedelta | complex | Sequence[Any] | set[Any] | Mapping[Any, Any] | NAType | None]"  [arg-type]
Fixed this by adding "frozenset" to the enumerated Callable output types.
Created a test case by calling series.Apply(frozenset) and running "poe mypy".
=> BUG/TST: fixed series apply frozenset error and created test case

.github/workflows/test.yml
Testing if changing the workflow from `macos-latest` to `macos-14` will fix the issue with `pytables`
=> change from macos-latest to macos-14

pandas-stubs/core/frame.pyi, pandas-stubs/core/groupby/generic.pyi, pandas-stubs/core/series.pyi, tests/test_frame.py, tests/test_series.py
I played around a bit and found that `Series.mask()` actually had the same issue as `DataFrame.mask()`:
```python
import pandas as pd
s = pd.Series([1]).mask(cond=lambda x: x % 2 == 1, other=2)
print(s)
```
```
(.venv) ➜  test python -m mypy test.py
test.py:2: error: Argument "cond" to "mask" of "Series" has incompatible type "Callable[[Any], Any]"; expected "Series[bool] | ndarray[Any, dtype[bool_]] | list[bool]"  [arg-type]
Found 1 error in 1 file (checked 1 source file)
```
I tried to fix both in this PR. The new `cond` types match those used in [`Series.where`](https://github.com/pandas-dev/pandas-stubs/blob/e63d1cbf5087cd7cd934db1c84184cb2caacbac9/pandas-stubs/core/series.pyi#L1420-L1426) and [`DataFrame.where`](https://github.com/pandas-dev/pandas-stubs/blob/e63d1cbf5087cd7cd934db1c8 …
=> Add callable condition type in Series.mask, DataFrame.mask

pyproject.toml, tests/test_frame.py, tests/test_groupby.py, tests/test_resampler.py, tests/test_series.py, tests/test_timefuncs.py, tests/test_windowing.py
Fixed the nightly tests.  Revealed some bugs in the dev code.
=> Update pyright, pandas, mypy versions.  Fix nightly tests

pandas-stubs/io/formats/style.pyi, tests/test_styler.py
- `test_styler.py:test_apply()` has a new test
=> Fix `Styler.apply()` to accept keyword arguments

tests/test_api_types.py
For some reason, `mypy` has trouble figuring out the type of `pd.api.interchange.from_dataframe`, but if you import it, the error goes away.
=> import from_dataframe

pandas-stubs/core/series.pyi, tests/test_series.py
- `test_operator_constistency` added in `test_series.py`
=> 748 series operator timedelta

pandas-stubs/_typing.pyi, pandas-stubs/core/resample.pyi, pandas-stubs/core/reshape/tile.pyi, pandas-stubs/core/series.pyi, pandas-stubs/plotting/_core.pyi, pyproject.toml, tests/__init__.py, tests/test_io.py, tests/test_pandas.py, tests/test_series.py, tests/test_utility.py
CI is now pulling in numpy 2.0, so this removes the numpy deprecated `np.float_` and changes it to `np.double`, which works with older and newer versions of  numpy.
In addition, there are a number of other changes where `numpy` has removed certain aliases for dtypes, so removed those from the tests.
Set up the CI to use numpy 1.x with python <=3.11, and numpy 2.0 with python=3.12 so both versions of numpy are tested.
=> Support numpy 2.0 in tests

pandas-stubs/_typing.pyi, pandas-stubs/core/series.pyi, tests/test_series.py
Only added the proposed changes so far. Will try to work on tests as soon as possible.
Does not seem to break any existing tests so far at least.
(I think the failures are all due to numpy 2.0 and separate from my changes)
=> Fix signature of Series.map()

pandas-stubs/_typing.pyi, pandas-stubs/core/dtypes/missing.pyi
This is to fix issues with pyright strict mode which complains about partially unknown types.
I verified that [this](https://github.com/pandas-dev/pandas-stubs/blob/main/tests/test_pandas.py#L319) test fails in strict mode without these changes and passes with them.
There are still some points i am unsure about:
- Whether to use `Any` or an (unbounded?) `TypeVar` (or maybe i should use `Incomplete`?)
- I had to split the `ArrayLike` annotation into its components to add the type parameters to the ndarray. While i did also change it in the `pandas-stubs/_typing.pyi`, it was still importing them from the actual pandas.
=> Add type parameters to generics in isna and notna

pandas-stubs/_typing.pyi, pandas-stubs/core/frame.pyi
Closes: https://github.com/pandas-dev/pandas-stubs/issues/946
I verified that the df.merge parts of [this](https://github.com/pandas-dev/pandas-stubs/blob/main/tests/test_merge.py#L17) test fail in pyright strict mode without these changes, and do not after these changes.
=> Add type parameters for types used in df.merge

pandas-stubs/_typing.pyi, pandas-stubs/core/frame.pyi
Adresses: https://github.com/pandas-dev/pandas-stubs/issues/952
Currently just added the explicit `Any` annotations everywhere, moved `ListLikeExceptSeriesAndStr` from a TypeVar to a Union and verified that more tests pass pyright strict mode.
However i still have a confusion about the overloads with `Mapping`. Isnt that just any generic object?
=> Add explicit type parameters to arguments of df.apply

.github/workflows/optional.yml, docs/tests.md, pyproject.toml, pyrightconfig-strict.json, scripts/test/_step.py, scripts/test/run.py
Setup a optional CI job that uses full pyright strict mode by taking its settings from `pyrightconfig-strict.json`.
Addresses the other points made here: https://github.com/pandas-dev/pandas-stubs/issues/952
=>  Setup optional CI jobs using pyright strict mode

pandas-stubs/core/series.pyi, tests/test_series.py
`Series.case_when()` added in pandas 2.2, so this adds it to the stubs.
- `test_series.py:test_case_when()`
=> add Series.case_when

pandas-stubs/core/reshape/concat.pyi
Steps are:
The first step is done. The second step does not work because of mypy. Those test failures also happen without the explicit `Any`.
=> Trying to make pd.concat work with pyright strict mode.

pandas-stubs/core/frame.pyi, tests/test_frame.py
`df.apply()` should allow Callables to return either an `S1` compatible type or `pd.NA`
=> df.apply should allow pd.NA from Callables

pandas-stubs/core/tools/timedeltas.pyi, tests/test_timefuncs.py
Should fix the issue in #956 with allowing the sequence of string type, I was not sure about the `assert_type` step above, please feel free to guide me on that one.
=> Switch to_timedelta argument type from list to Sequence

pandas-stubs/core/frame.pyi, tests/test_frame.py
`items` can be `ListLike`
It is turned into and `Index` which can handle and `ListLike` as data
https://github.com/pandas-dev/pandas/blob/9b375be5aa3610e8a21ef0b5b81e4db04270f3d3/pandas/core/generic.py#L5448
=> fix signature of frame.filter

pandas-stubs/core/frame.pyi, tests/test_frame.py
=> Allow 'integer' in select_dtypes include argument

.github/setup/action.yaml, .github/workflows/test.yml, pyproject.toml
I checked the jobs and they are doing the right things in terms of testing numpy > 2.0 and < 2.0 on ubuntu, and < 2.0 on windows and macos
=> set up workflows to test numpy 1.x and 2.0

pandas-stubs/core/frame.pyi, tests/test_frame.py
=> Add support for arrays in `lower` and `upper` args of `DataFrame.clip`

pandas-stubs/_typing.pyi, tests/test_frame.py
4 and 5 added in 3.12 (python/cpython/67230)
ref: https://docs.python.org/3/library/csv.html#csv.QUOTE_NOTNULL
ref: https://github.com/python/cpython/blob/a8bc03696c7c2c03e1d580633151ec7b850366f3/Modules/_csv.c#L88-L106
=> Validate all values for csv.QUOTE

pandas-stubs/core/base.pyi, pandas-stubs/core/frame.pyi, pandas-stubs/core/series.pyi, tests/test_frame.py, tests/test_indexes.py, tests/test_series.py
=> Complete signature of value_counts

README.md, pyproject.toml
=> Remove references to Python 3.9

pandas-stubs/io/sql.pyi, tests/test_io.py
- As explained in https://github.com/pandas-dev/pandas-stubs/issues/996, the added types are _not_ valid for SQLite databases/drivers, so it's not possible to add a test that actually executes without major changes to the CI setup. But I've added a skipped test instead so that at least the [type checking part](https://github.com/pandas-dev/pandas-stubs/blob/fa7e4446d226ee385412186bc3414a3499f42917/.github/workflows/test.yml#L35-L39) of the CI pipeline can check if the new annotations are at all sane.
=> Allow tuple-valued params in read_sql[_query]

pandas-stubs/core/series.pyi, tests/test_frame.py
=> GH978 Build pd.Series from typed dict

pandas-stubs/core/indexes/range.pyi, tests/test_indexes.py
=> GH677 Allow pd.RangeIndex to be initialized with range

pandas-stubs/_libs/tslibs/offsets.pyi, tests/test_timefuncs.py
=> GH648 Allowing dateoffset weekday from relativedelta

pyproject.toml, tests/test_utility.py
Test with pandas 2.2.3.  Seems like `show_versions()` got fixed.
=> Bump to pandas 2.2.3

pandas-stubs/core/groupby/generic.pyi, tests/test_frame.py
=> GH1025 Typehint DataFrame.groupby.value_counts method

pandas-stubs/core/frame.pyi, pandas-stubs/core/series.pyi, tests/test_frame.py, tests/test_series.py
Hi! 
Seeing the issue was a bit old I thought it was a good opportunity to give it a try, hope that's ok.
This PR adds the missing limit_area parameter to the `ffill` and `bfill` method to match the implementation in the [main pandas](https://github.com/pandas-dev/pandas/blob/v2.2.3/pandas/core/generic.py#L7688) repo. (also adds tests)
=> GH987 Add limit_area parameter in `ffill` and `bfill` methods

pandas-stubs/core/series.pyi, tests/test_frame.py
Potential fix for #571 to typehint a `Series` created from an empty list to be typed as `pd.Series[Any]`.
Open for feedback if this is not the optimal type.
=> GH571 Update typehint when creating a Series from an empty list

pandas-stubs/core/frame.pyi, pandas-stubs/core/series.pyi, tests/test_frame.py, tests/test_series.py
- Additionally add overloads to dataframe `drop_duplicates` method
- Additionally convert existing tests of DF `drop_na` method to use `assert_type`.
=> Add `ignore_index` keyword arg in `dropna` and `drop_duplicates` (Part of GH624)

pandas-stubs/core/series.pyi, tests/test_series.py
=> GH1039 Clear tests and add typehint for Series.unique with datetime/timedelta

pandas-stubs/io/json/_json.pyi, tests/test_io.py
=> GH1033 Add overloads of engine for pd.read_json

pandas-stubs/core/frame.pyi, tests/test_frame.py
=> GH1045 Split overload of groupby on as_index for all cases

docs/setup.md, pandas-stubs/core/frame.pyi, pandas-stubs/core/series.pyi, tests/test_frame.py, tests/test_series.py
Note that the four failing tests also fail on `main` and are unrelated to these changes:
```
FAILED tests/test_series.py::test_astype_float['f16'-<class 'numpy.longdouble'>] - TypeError: data type 'f16' not understood
FAILED tests/test_series.py::test_astype_float['float128'-<class 'numpy.longdouble'>] - TypeError: data type 'float128' not understood
FAILED tests/test_series.py::test_astype_complex['c32'-<class 'numpy.clongdouble'>] - TypeError: data type 'c32' not understood
FAILED tests/test_series.py::test_astype_complex['complex256'-<class 'numpy.clongdouble'>] - TypeError: data type 'complex256' not understood
```
=> Fix `Series.rename_axis` and `DataFrame.rename_axis` typing

pandas-stubs/_typing.pyi, pandas-stubs/core/frame.pyi, tests/test_frame.py
I haven't added tests since JoinHow doesn't seem to be tested in any case. Should I add some? Merge tests unimpacted.
=> GH1043 Update _typing.pyi: add "cross" option to JoinHow

pandas-stubs/io/excel/_base.pyi, tests/test_io.py
I'm struggling with my NixOs setup, I've managed to run mypy tests but not pyright because it wants to install node, and I'm still a newbie with development on nix...
I hope everything is OK
=> GH1061 add calamine literal to ExcelFile engine

pandas-stubs/api/typing/__init__.pyi, tests/test_api_typing.py
=> GH1055 Add pandas.api.typing to pandas-stubs

pandas-stubs/__init__.pyi, pandas-stubs/_libs/tslibs/timestamps.pyi, pandas-stubs/core/frame.pyi
=> GH1065 timestamp freq argument and DataFrame/Series.mask

tests/test_frame.py
A change was made to `typeshed` to make `slice` a `Generic`, which is causing the `mypy_nightly` tests to fail.  More discussion here:
https://github.com/python/mypy/issues/18225
This fix should allow the CI to pass as well as the `mypy_nightly` runs.  See comment in code.
=> adjust test for slice due to typeshed changes

pyproject.toml
=> Lock numpy upper bound version due to bug in version 2.2.0

pandas-stubs/core/indexes/base.pyi, pandas-stubs/core/indexes/interval.pyi, pandas-stubs/core/indexes/multi.pyi, pandas-stubs/core/indexes/range.pyi, pandas-stubs/core/series.pyi, pyproject.toml
=> Add MaskType to other cases

pandas-stubs/core/frame.pyi, tests/test_frame.py
-  Closes #1076 
- Tests added:
Missing parameter for the sort argument of the pandas.DataFrame.pivot_table method added and implemented tests
=> fixed pivot_table sort argument in pandas_stubs

pyproject.toml, tests/test_scalars.py, tests/test_series.py
Revert the version restriction for numpy as numpy released a 2.2.1 version.
=> GH1071 Revert numpy version restriction

tests/test_frame.py, tests/test_groupby.py, tests/test_indexes.py, tests/test_interval.py, tests/test_interval_index.py, tests/test_pandas.py, tests/test_timefuncs.py
=> GH1089 Fix pandas nightly and migrate tests to new framework

.github/workflows/comment_commands.yml
Issue came from the fact that the checkout was only pulling main and not the branch on which the PR was at, this PR fixes that by retrieving the correct branch name and passing it to the `checkout` github action to pull the correct branch and not main (which is the default).
=> GH1090 Fix comment commands not checking out the correct branch

pandas-stubs/core/series.pyi, tests/test_series.py
`pyright` with strict type checking is inferring that a list of mixed int and float is `list[int | float]`, so created overloads for `Series.__new__()` that makes that a `Series[float]`.
=> handle pyright inferring mixed float and int lists

pandas-stubs/core/construction.pyi, pandas-stubs/core/frame.pyi, pandas-stubs/core/generic.pyi, pandas-stubs/core/indexes/datetimes.pyi, pandas-stubs/core/reshape/encoding.pyi, pandas-stubs/core/series.pyi, tests/test_frame.py, tests/test_series.py
=> Type `tolerance` in `reindex_like`, remove unused function

pandas-stubs/io/excel/_base.pyi, tests/test_io.py
The changes make the signature of
https://github.com/pandas-dev/pandas-stubs/blob/4976e11dbdbaf740ea5a7059d330a7f0a5305f2e/pandas-stubs/io/excel/_base.pyi#L246-L251
consistent with the run time version:
https://github.com/pandas-dev/pandas/blob/0691c5cf90477d3503834d983f69350f250a6ff7/pandas/io/excel/_base.py#L1507-L1513
* The first argument name should be `path_or_buffer`, not `io`. (The property `ExcelFile(...).io` is correct. No need to change this.)
* The keyword `engine_kwargs` is added.
* ~~The keyword `storage_options` should allow a `None` value.~~ Sorry, I found that `None` case has been included [here](https://github.com/pandas-dev/pandas-stubs/blob/4976e11dbdbaf740ea5a7059d330a7f0a5305f2e/pandas-stubs/_typing.pyi#L614). No need to make changes for this.
=> Make `pandas.ExcelFile(...)` in stubs consistent with the run time version.

pandas-stubs/core/series.pyi, tests/test_series.py
=> type Series.info

pandas-stubs/core/frame.pyi, pandas-stubs/core/generic.pyi, pandas-stubs/core/series.pyi, tests/test_series.py
The return value of these methods varies on the `inplace` argument.
=> Simplify and fix overloads for methods with `inplace` parameter

pandas-stubs/_typing.pyi, pandas-stubs/core/indexes/datetimes.pyi
This came up in another PR (https://github.com/pandas-dev/pandas-stubs/pull/1107#discussion_r1946700293)
It seems that the definitions have slightly drifted - OK to align them?
=> Align AnyArrayLike with pandas._typing definition

tests/test_frame.py, tests/test_series.py
=> GH1089Fix nightly for pandas 3.0.0 due to future warnings

pandas-stubs/core/indexes/multi.pyi, tests/test_indexes.py
=> type multiindex constructors

pandas-stubs/_typing.pyi, pandas-stubs/core/frame.pyi, pandas-stubs/core/series.pyi, tests/test_frame.py, tests/test_series.py
=> type dataframe.replace

pandas-stubs/core/groupby/generic.pyi, tests/test_groupby.py
=> type bins in seriesgroupby.value_counts

pandas-stubs/core/indexes/base.pyi, pandas-stubs/core/series.pyi, pyproject.toml
pyright changed some logic with figuring out overlapping overloads.
=> support pyright 1.1.396 and mypy 1.15.0

pandas-stubs/io/formats/style.pyi, tests/test_styler.py
- Addition of `index` and `columns` to Styler in `style.pyi`
- Addition of tests in tests/test_style.py for testing `index` and `columns`
- https://github.com/pandas-dev/pandas/issues/60815
- https://github.com/pandas-dev/pandas/pull/60979
```
from typing_extensions import reveal_type
import pandas as pd
from pandas.io.formats import style as pd_style
def f(s: pd_style.Styler) -> pd_style.Styler:
print(s.columns)
fmt = "{:.2%}"
return s.format(fmt)
df = pd.DataFrame({"a": [1, 2, 3]})
df2 = df.style.pipe(f)
reveal_type(df2)
```
**Output:**
```
$ mypy pandas-stubs/mytest/t.py
pandas-stubs/mytest/t.py:14: note: Revealed type is "pandas.io.formats.style.Styler"
Success: no issues found in 1 source file
```
First PR on pandas-stubs, your feedback will be highly valuable to me, Thanks!
=> Add `index` and `columns`  as properties to Styler

.github/workflows/comment_commands.yml
Fix comment commands to source branches to run nightly tests in correct repo
=> Fix comment commands to source branches 

pandas-stubs/core/groupby/generic.pyi
- `axis` has been deprecated from groupby methods (https://github.com/pandas-dev/pandas/pull/57109/files)
- `corrwith` has been deprecated on pandas main - is it OK to already remove it from here, or should that wait until 3.0 actually comes out?
- grouped `fillna` has been deprecated since 2.2
=> clean: Groupby deprecations

pandas-stubs/core/frame.pyi, tests/test_frame.py
=> type dataframe.combine

.github/workflows/test.yml, pyproject.toml
=> GH1052 python 3.13 support

pandas-stubs/core/frame.pyi, pandas-stubs/core/series.pyi, tests/test_frame.py, tests/test_series.py
=> type align

pandas-stubs/core/indexes/base.pyi, pandas-stubs/core/series.pyi, tests/test_series.py
Added some test framework migration as this was how I originally found the issue with `rename`
=> GH1139 Series.rename inplace

pyproject.toml, tests/test_frame.py, tests/test_plotting.py
=> GH1147 Drop version restriction on matplotlib and prevent test to write to root folder

README.md
Since https://github.com/pandas-dev/pandas-stubs/pull/1092, this badge shows up as green, so I think it could be added to the README now?
Badge info: https://shields.io/badges/py-pi-types
=> Add "typing: stubs" badge

pandas-stubs/_typing.pyi, pandas-stubs/core/frame.pyi, tests/test_frame.py, tests/test_series.py
=> Fix: DataFrame.replace incompatible with type "dict[str, dict[int, int]]"

pandas-stubs/core/series.pyi
ref #1168
These are all cases where `kwargs` / `args` just exist for compatibility with numpy
Exceptions are:
- `to_numpy`, where the kwargs get passed to the extensionarray. Given that third parties can develop their own extensionarrays, I think this one really should be `Any`, we can't know what arguments third party EA authors will accept?
- `pct_change`: this could be more precise, have opened https://github.com/pandas-dev/pandas-stubs/issues/1169 about that
=> type args and kwargs as Any in series.pyi

pandas-stubs/_typing.pyi, pandas-stubs/core/frame.pyi, tests/test_frame.py
=> type DataFrame.assign

pandas-stubs/_typing.pyi, tests/test_frame.py, tests/test_series.py
=> GH1182 Add numpy integer, floating, complex to Scalar

pandas-stubs/core/series.pyi, tests/test_series.py
Implements the suggested solution + tests in https://github.com/pandas-dev/pandas-stubs/issues/941#issuecomment-2289142525
=> GH941 add `UnknownSeries` overload for `Series.map`

pandas-stubs/core/indexes/multi.pyi, tests/test_indexes.py
I think we'll need to wait for https://github.com/pandas-dev/pandas/issues/61357 to be fixed before merging this
=> GH1158 change type of tuples param for MultiIndex.from_tuples

pandas-stubs/core/indexes/base.pyi, pandas-stubs/core/indexes/datetimes.pyi, pandas-stubs/core/indexes/timedeltas.pyi, tests/test_indexes.py
=> GH828 Replace Iterable with Axes for Index.__new__/Index.__init__

pandas-stubs/_typing.pyi, pandas-stubs/core/tools/datetimes.pyi, tests/__init__.py, tests/extension/decimal/array.py, tests/test_api_typing.py, tests/test_dtypes.py, tests/test_frame.py, tests/test_indexes.py, tests/test_io.py, tests/test_pandas.py, tests/test_scalars.py, tests/test_series.py, tests/test_string_accessors.py, tests/test_styler.py, tests/test_testing.py, tests/test_timefuncs.py
In preparation for an eventual change in `pyright` that would ban private imports, I have moved the private imports for the tests into `tests/__init__.py`.  
Also will be working to make some of the current private imports public as reflected in the discussion here:  
https://github.com/pandas-dev/pandas/issues/55231#issuecomment-2833691635
=> move private imports from testing into tests/__init__.py

pandas-stubs/core/frame.pyi, pandas-stubs/core/series.pyi, tests/test_frame.py, tests/test_series.py
Turns out there is a nasty edge case when you pass everything as None for upper and lower and ask for `inplace=True`, it will return `Self` and not `None`.
=> GH984 Add overload for DataFrame.clip and update those for Series.clip

pandas-stubs/api/__init__.pyi, pandas-stubs/api/typing/__init__.pyi, pandas-stubs/core/arrays/datetimes.pyi, pandas-stubs/core/dtypes/dtypes.pyi, pandas-stubs/core/frame.pyi, pandas-stubs/core/indexes/accessors.pyi, pandas-stubs/core/indexes/datetimes.pyi, pandas-stubs/core/indexes/multi.pyi, pandas-stubs/core/series.pyi
=> GH1221 Fix typing module exposure in pandas.api

pandas-stubs/_config/__init__.pyi, pandas-stubs/api/__init__.pyi, pandas-stubs/api/extensions/__init__.pyi, pandas-stubs/api/indexers/__init__.pyi, pandas-stubs/core/dtypes/base.pyi, pandas-stubs/core/dtypes/dtypes.pyi, pandas-stubs/core/interchange/__init__.pyi, pandas-stubs/io/__init__.pyi, pandas-stubs/io/formats/__init__.pyi, pandas-stubs/io/json/__init__.pyi
=> GH1227 align init pyi with init py from pandas

pandas-stubs/io/parsers/readers.pyi, tests/test_io.py
=> GH963 Restrict callable to hashableT for read_csv

pyproject.toml, tests/test_frame.py
=> GH1235 Update to mypy 1.16

pandas-stubs/_config/config.pyi, tests/test_config.py
Updated based off documentation in [config_init.py](https://github.com/pandas-dev/pandas/blob/main/pandas/core/config_init.py)
Let me know if you'd like me to update the second test to also use `assert_type` on each value.
=> GH1230 Improve types for pd.options.display.* properties

pandas-stubs/core/frame.pyi, pandas-stubs/core/generic.pyi, pandas-stubs/core/indexes/base.pyi, pandas-stubs/core/series.pyi, pandas-stubs/core/strings.pyi
These aliases are not needed as they are there to avoid name collisions with methods defined in the class. Name collisions can be avoided by importing these symbols from `builtins` under a different name. This has no functional change to type checkers but has two tiny advantages:
1. IDEs now display the type as builtin type instead of an alias that doesn't exist at runtime
2. Linters like ruff can now understand that the symbol used is exactly the builtin one and can detect more bad usages (see the comment below)
=> Replace aliases to builtins with imports

pandas-stubs/_typing.pyi, pandas-stubs/core/groupby/base.pyi, pandas-stubs/core/groupby/generic.pyi, tests/test_series.py
=> GH456 First attempt GroupBy.transform improved typing

pandas-stubs/_typing.pyi, tests/test_frame.py
Following #1250, `DataFrame.assign()` should allow `Sequence`s, e.g. `tuple`s
```py
import pandas as pd
df = pd.DataFrame({"a": (1,2,3)})
df = df.assign(d=lambda df: (10,20,30))
```
Need to update `IntoColumn` in `_typing.pyi` to include `Sequence[Scalar]`
- OS: Windows 11
- python version: 3.10
- `mypy` 1.16.0
- version of installed `pandas-stubs` :  development version
=> fix: assign Sequences

pandas-stubs/_typing.pyi, pandas-stubs/core/series.pyi, tests/test_series.py
=> GH1255 Improve index typing for Series

pandas-stubs/core/indexes/timedeltas.pyi, tests/test_timefuncs.py
As of pandas 2.0, `pd.timedelta_range` allows passing a `unit` argument which controls the underlying precision of the returned timedeltas ([link](https://github.com/pandas-dev/pandas/blob/f94b430126efbe4a3078f95e90846a4d6161448a/pandas/core/indexes/timedeltas.py#L240-L272)).  This PR updates the type stub to reflect this.
=> Include `unit` argument in `timedelta_range` type stub

tests/test_series.py
@cmp0xff noticed that the wrong behavior (pd.Series[Any]) was not the case anymore so this PR only adds tests to ensure the behavior.
=> GH1149 Add testing for pd.Series.str behavior

pyproject.toml, tests/test_frame.py, tests/test_series.py, tests/test_string_accessors.py
NIghtly runs failed due to tests related to passing in compiled regex when using pyarrow.  This also identified a couple of bugs in pandas with the new string Dtype
@twoertwein also thanks for reviews while I was on vacation!
=> fix nightly runs

tests/test_string_accessors.py
Looks like the nightly changed and it uncovered a few more pandas bugs with arrow strings
=> more bugs in arrow string types for nightly to work

pandas-stubs/core/frame.pyi, pandas-stubs/core/series.pyi, tests/series/test_series.py, tests/test_frame.py
=> GH1307 Add Timedelta for tolerance arg in DataFrame/Series.reindex

pandas-stubs/core/frame.pyi, tests/test_frame.py
=> GH1299 Allow for Index and Series in the second argument of DataFrame.loc

pandas-stubs/core/series.pyi, tests/series/arithmetic/bool/test_add.py, tests/series/arithmetic/complex/test_add.py, tests/series/arithmetic/int/test_add.py, tests/series/arithmetic/test_add.py
This is inspired by #1274 and a follow-up for #1275.
=> feat(series): addition for bools

pandas-stubs/core/series.pyi, tests/series/arithmetic/bool/test_truediv.py, tests/series/arithmetic/complex/test_truediv.py, tests/series/arithmetic/float/test_truediv.py, tests/series/arithmetic/test_truediv.py, tests/series/test_series.py
This is inspired by https://github.com/pandas-dev/pandas-stubs/pull/1312#issuecomment-3168718063 and a follow-up for #1311.
=> feat(series): add and truediv for bools

pyproject.toml
I figured that since scipy is a dependency, and we like static typing around here, it would probably help to add some stubs for it too :). See https://github.com/scipy/scipy-stubs for details.
=> add `scipy-stubs` to the `dev` dependency group

pandas-stubs/core/base.pyi, pandas-stubs/core/series.pyi, tests/indexes/test_indexes.py
=> type IndexOpsMixin
