pandas-dev/pandas-stubs

runtests.bat, tests/pandas/test_frame.py, tests/pandas/test_indexes.py, tests/pandas/test_pandas.py, tests/pandas/test_series.py, typings/pandas/core/frame.pyi, typings/pandas/core/indexes/api.pyi, typings/pandas/core/indexes/base.pyi, typings/pandas/core/reshape/concat.pyi, typings/pandas/core/series.pyi
Have converted test_frame, test_indexes, test_pandas, test_series
Had to add missing `pandas/core/indexes/api.pyi`
=> use assert_type instead of check_XXX in some tests

.github/pull_request_template.md
Remind people to close open issues and add tests for type annotations.
=> CI: PR template

tests/test_frame.py, tests/test_pandas.py, tests/test_series.py
Catch all warning generated during testing
=> MAINT: Catch all warnings

.github/workflows/test.yml
xref #121
There was also a [poetry update today](https://github.com/python-poetry/poetry/releases/tag/1.1.14), maybe that caused some weird issues.
=> cache poetry.lock for each OS/python version/poetry version

.github/workflows/test.yml, pyproject.toml, scripts/test/__init__.py, scripts/test/_step.py, scripts/test/run.py
closes #68
The dist test run locally fine for me without having to create this file.
=> is the mypy_pkg_file needed?

docs/setup.md, docs/style.md, docs/tests.md, scripts/test/__init__.py, scripts/test/_step.py, scripts/test/run.py
=> Run pre-commit through poe

.github/workflows/test.yml
=> don't upgrade pip

pandas-stubs/_typing.pyi, tests/test_frame.py
Please let me know, if there is anything else I should add
cc @twoertwein
=> BUG: groupby not accepting list[str] as by argument

pandas-stubs/_typing.pyi, pandas-stubs/core/frame.pyi, tests/test_frame.py
- `test_frame.py:test_generic()`
=> use Union for ListLike in DataFrame __new__

pandas-stubs/_testing/__init__.pyi, tests/test_frame.py, tests/test_pandas.py, tests/test_series.py, tests/test_testing.py
Add stub to allow usage in io testing
=> ENH: Add stub for ensure_clean

pandas-stubs/core/frame.pyi, pandas-stubs/io/gbq.pyi
=> ENH: Synchronize gbq with upstream

.github/workflows/test.yml, pyproject.toml
Seeing if the change in poetry is cause of failures on windows
=> pin poetry to 1.1.15

pandas-stubs/io/sql.pyi, tests/test_io.py
=> ENH: Add Selectable

pandas-stubs/__init__.pyi, pandas-stubs/core/reshape/api.pyi, pandas-stubs/core/reshape/encoding.pyi, pandas-stubs/core/reshape/reshape.pyi, tests/test_utility.py
=> ENH: Add from_dummies

tests/test_frame.py, tests/test_pandas.py, tests/test_scalars.py, tests/test_timefuncs.py
Made changes to the tests to fix the current set of nightly run errors.
=> Fix nightly runs

pandas-stubs/_typing.pyi, pandas-stubs/core/frame.pyi, pandas-stubs/core/groupby/generic.pyi, pandas-stubs/core/series.pyi, tests/test_frame.py
=> Add RandomState support for df sampling

.github/workflows/optional.yml
=> CI: use python 3.11 for the nightly tests

pyproject.toml, tests/test_frame.py
Updating `mypy` and `pyright` versions.  Required a change to a test that `pyright` now correctly picks up.
=> Support mypy 1.1.1 and pyright 1.1.300

.pre-commit-config.yaml, tests/test_frame.py, tests/test_series.py
=> CI: fix nightly

pandas-stubs/core/frame.pyi, tests/test_frame.py
=> allow passing lists as values to `locframe.__setitem__`

scripts/test/run.py
=> Use new nightly wheels' location

tests/test_errors.py
=> Fix nightly, yet again

pyproject.toml
Update mypy to 1.5.0
UPdate pyright to 1.1.322
=> update mypy and pyright versions

pandas-stubs/core/generic.pyi, pandas-stubs/core/series.pyi, tests/test_frame.py, tests/test_series.py
=> add convert_floating argument to convert_dtypes

pandas-stubs/core/series.pyi, tests/test_series.py
=> Enable construction of pd.Series with NaT and NA

README.md
=> copy paste from pandas readme, resolves #909

pyproject.toml
relaxing the constraint on numpy to match pandas itself https://github.com/pandas-dev/pandas/blob/main/pyproject.toml#L30-L31
syntax reference: https://python-poetry.org/docs/dependency-specification/#multiple-constraints-dependencies
=> relax numpy versioning

.github/setup/action.yaml, .github/workflows/test.yml
=> GH1006 Update workflows version 

pandas-stubs/_libs/tslibs/timedeltas.pyi, tests/test_timefuncs.py
=> accept float values in pd.Timedelta

pandas-stubs/core/frame.pyi, tests/test_frame.py
=> GH1203 Pass a dict to setter for DataFrame.loc/iloc 

pandas-stubs/_typing.pyi
=> remove Any from np.ndarray declarations in _typing.pyi

pandas-stubs/core/series.pyi, tests/test_series.py
=> GH1241 Add cumsum method on TimedeltaSeries
